services:
  sqlserver:
    container_name: backoffice-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_COLLATION=Modern_Spanish_CI_AS
    ports:
      - '1433:1433'
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          '/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q ''SELECT 1'' -C -b || exit 1'
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backoffice-net

  prisma-studio:
    image: node:22-slim
    container_name: backoffice-prisma-studio
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c " apt-get update -y && apt-get install -y openssl && npx prisma studio "
    ports:
      - '5555:5555'
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlserver://sqlserver:1433;database=${MSSQL_DB_NAME};user=sa;password=${MSSQL_SA_PASSWORD};encrypt=false;trustServerCertificate=true
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - backoffice-net

volumes:
  sqlserver_data:

networks:
  backoffice-net:
    driver: bridge
