export const ErrorCodes = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  USER_NOT_REGISTERED: 'USER_NOT_REGISTERED',
  USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',
  NO_PERMISSIONS: 'NO_PERMISSIONS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
